### ISSUE TITLE
The problem of account login

### ISSUE THREAD

**Issue by cainiaoYJ** [tunogya/aai-app#17]
I accidentally logged out someday and  I can‘t login any more.
I'm a chatGPT-4 user.
![problem](https://github.com/tunogya/abandonai-app/assets/71686247/f8efe9d3-7fe0-49c7-96cf-de86fecb157e)

**Comment by tunogya** [comment]
In this case, there is no accident that you are frozen by the risk control system. We have recently found that some users maliciously abuse GPT-4 tokens, which seriously affects the normal use of other users. Please contact tom@abandon.ai with your account information.
